### PR TITLE
Update click version 6 -> 7

### PR DESCRIPTION
**Pull request by jbaum98**
No code changes are necessary other than bumping the version number.

### CODE REVIEW

**Comment by thebigmunch** [comment]
Restricting to ``^7.0`` isn't right here. But I was planning to change the requirements to allow ``>=6, <8`` as I've actually had 7 installed locally for months now. The next release (coming soon, likely today) should have what you need there.

The change to setup.py wouldn't actually be required as far as google-music-scripts, as the constraint already allows for 7. Does it actually need to be ``>=7`` for the Nix package? Or does it just have to support ``>=7``? I should really have a ceiling of ``<8`` there, but it's actually just a shim until pip and services support properly installing non-setuptools packages.

PS Thanks for the Nix package. Glad the love gets spread. I'll have to link to it when it gets in.

**Comment by thebigmunch** [comment]
PPS The only reason I haven't pushed that commit yet is that includes other version bumps of dependencies that I have to release first : )

**Comment by jbaum98** [comment]
> PPPS You should definitely always give an explanation as to why you want a change, rather than leaving a developer/maintainer to go to a linked issue to read and find out ^_^

Noted, sorry about that.

> The next release (coming soon, likely today) should have what you need there.

Okay awesome, I'll just wait for the new release.

> The change to setup.py wouldn't actually be required as far as google-music-scripts, as the constraint already allows for 7. Does it actually need to be `>=7` for the Nix package? Or does it just have to support `>=7`? I should really have a ceiling of `<8` there, but it's actually just a shim until pip and services support properly installing non-setuptools packages.

It just needs to support click 7 because that's the version in `nixpkgs` right now.

> PS Thanks for the Nix package. Glad the love gets spread. I'll have to link to it when it gets in.

Love the tool, thanks for you work!

**Comment by thebigmunch** [comment]
Released.

**Pull request closed without merging**
